name: Jest

on:
  pull_request:
    branches: [main]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn

      - name: Jest Test 22
        run: yarn test
