name: Jest2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn

      # - name: Install modules
      # - run: yarn

      - name: Run tests
        run: yarn test
