name: Jest

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Install modules
      #   run: yarn
      # - run: yarn

      - name: Run tests
        run: yarn test
