name: Jest

on:
  pull_request:
    branches: [main]
  push:
    branches: [test]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install module
        run: yarn

      - name: Build
        run: yarn build

      - name: Jest
        run: yarn test
